### ISSUE TITLE
Support Pagination of Studies

### ISSUE THREAD

**Issue by dzelemba** [GoogleCloudPlatform/weasis-chcapi-extension#5]
Use limit/offset query parameters to allow viewing past the first 100 studies.

**Comment by pavertomato** [comment]
since API does not return amount of studies in store we have two options how to display pages:

1.  display only buttons "previous" and "next" for navigation as OHIF does
2.  request all studies  and build navigation block when we know how many studies we have to get something like this
![image](https://user-images.githubusercontent.com/878990/58105619-00ba2c00-7c11-11e9-9acf-7e197838e44a.png)
    2.1 request first page, display it, in background request all that left and display navigation block

**Comment by dzelemba** [comment]
Let's go with option #1 for now. 

We're working on returning number of remaining studies in the QIDO response, so we can potentially update once we have that.

**Comment by pavertomato** [comment]
> We're working on returning number of remaining studies in the QIDO response, so we can potentially update once we have that.

great
